### ISSUE TITLE
cannot import name 'SnorkelSession'

### ISSUE THREAD

**Issue by iti-nlp** [snorkel-team/snorkel-extraction#2]
Just to clarify, my question is in regards to snorkel-extraction package as I am trying to run tutorial notebooks in this repo.

I looked at the other issues about the same problem in Snorkel repo. However I am still not able to figure it out. 

I followed all the steps in the installation instruction successfully for snorkel extraction. When I load the tutorials notebook, none of the 'from snorkel' import works. Only 'import snorkel' command works. 

I also  downloaded the original Snorkel package and the notebooks there works without any problem. I am wondering if it's something new because of the change in Snorkel version? I was interested in running the advanced tutorials under Snorkel Extraction.

Thank you!

**Comment by vincentschen** [comment]
hi @iti-nlp — thanks for bringing this up! 

I tried a clean install using the README instructions and wasn't able to reproduce this in the command line or jupyter.

```
(snorkel-extraction) ➜  snorkel-extraction git:(master) python
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import snorkel
>>> from snorkel import SnorkelSession
```

A few things to try:
* This repo _does not_ use the latest v0.9 Snorkel. Make sure you're installing Snorkel v0.7, which can be safely done by calling `pip uninstall snorkel; pip install .` from the root directory of this repo. 
* This tripped me up in the past: can you make sure that you have the right kernel in the jupyter notebook?
![image](https://user-images.githubusercontent.com/5819303/63653735-8fb17580-c725-11e9-9187-9171569630eb.png)
